from .Constant import GAMENAME

from BaseClasses import Location


class ZrothLocation(Location):
    game: str = GAMENAME

    def __init__(self, player: int, name: str = '', address: int = None, parent=None):
        super(ZrothLocation, self).__init__(player, name, address, parent)
        self.event = address is None


Zroth_location = {
    "POH00": "WoodD5",
    "POH01": "WoodUp",
    "POH02": "Wood",
    "POH03": "WoodBottom",
    "POH04": "Gutter",
    "POH05": "KakLedge",
    "POH06": "KakBack",
    "POH07": "Lake",
    "POH08": "LakeD2",
    "POH09": "Lake",
    "POH10": "Desert",
    "POH11": "Gutter",
    "POH12": "FieldLedge",
    "POH13": "MntBack",
    "POH14": "MntRight",
    "POH15": "Desert",
    "POH16": "Desert",
    "POH17": "Desert",
    "POH18": "Desert",
    "POH19": "GerLedge",
    "POH20": "Gutter",
    "POH21": "Shadow",
    "POH22": "TurtleTop",
    "POH23": "Land",
    "POH24": "Lake",
    "POH25": "D2Cave",
    "POH26": "MonsterMan",
    "POH27": "MonsterMan",
    "POH28": "MonsterMan",
    "POH29": "MonsterMan",
    "POH30": "MonsterMan",
    "POH31": "MonsterMan",
    "POH32": "Kak",  # Game
    "POH33": "Kak",  # Tavern
    "POH34": "Desert",  # Games
    "POH35": "Shadow",
    "Shield": "LinksHouse",
    "Sword1": "Wood",
    "Medalion2": "WoodD5",
    "Medalion1": "Desert",
    "Bottle2": "Desert",
    "Bottle1": "Kak",
    "Bow": "kak",
    "Medalion3": "Lake",
    "Bottle3": "Shadow",
    "Book": "BookCave",
    "DoubleMagic": "Land",
    "D1Map": "D1",
    "D1Compass": "D1",
    "D1K1": "D1",
    "D1K2": "D1",
    "D1K3": "D1",
    "D1Boss": "D1",
    "D1Object": "D1",
    "D1Crystal": "D1",
    "D2Map": "D2",
    "D2Compass": "D2",
    "D2K1": "D2",
    "D2K2": "D2",
    "D2K3": "D2",
    "D2K4": "D2",
    "D2K5": "D2",
    "D2Boss": "D2",
    "D2Object": "D2",
    "D2Crystal": "D2",
    "D3Map": "D3",
    "D3Compass": "D3",
    "D3K1": "D3",
    "D3K2": "D3",
    "D3K3": "D3",
    "D3K4": "D3",
    "D3K5": "D3",
    "D3Boss": "D3",
    "D3Object": "D3",
    "D3Crystal": "D3",
    "D4Map": "D4",
    "D4Compass": "D4",
    "D4K1": "D4",
    "D4K2": "D4",
    "D4K3": "D4",
    "D4Boss": "D4",
    "D4Object": "D4",
    "D4Crystal": "D4",
    "D5Map": "D5",
    "D5Compass": "D5",
    "D5K1": "D5",
    "D5Boss": "D5",
    "D5Object": "D5",
    "D5Crystal": "D5",
    "D6Map": "D6",
    "D6Compass": "D6",
    "D6K1": "D6",
    "D6K2": "D6",
    "D6K3": "D6",
    "D6Boss": "D6",
    "D6Object": "D6",
    "D6Crystal": "D6",
    "D7Map": "D7",
    "D7Compass": "D7",
    "D7K1": "D7",
    "D7K2": "D7",
    "D7Boss": "D7",
    "D7Object": "D7",
    "D7Crystal": "D7",
    "D8Map": "D8",
    "D8Compass": "D8",
    "D8K1": "D8",
    "D8K2": "D8",
    "D8Boss": "D8",
    "D8Object": "D8",
    "MSword": "D8",
    "D9Map": "D9",
    "D9Compass": "D9",
    "D9K1": "D9",
    "D9K2": "D9",
    "D9K3": "D9",
    "D9K4": "D9",
    "D9Boss": "D9",
    "Triforce": "D9",
}
